### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [cmouse/yahttp#17]
I would like to point out that an identifier like “[`_YAHTTP_URL_HPP`](https://github.com/cmouse/yahttp/blob/52852866df6c91b730a5dc2cc93bda9aa92d79ef/yahttp/url.hpp#L1 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by cmouse** [comment]
I suppose I could use `#pragma once`.

**Comment by elfring** [comment]
I would appreciate if [these identifiers will become standard compliant](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?").

**Comment by cmouse** [comment]
The identifiers have been now removed with 11be77a1fc4032ed268cb5a80eb2aa1d14ce849d
